minimum_pre_commit_version: 3.2.0
default_install_hook_types: [pre-commit,commit-msg,pre-push]
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [post-commit,push]